service: aws-billing-to-slack

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.9

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ce:GetCostAndUsage"
          Resource: "*"
          # Needed to get account alias
        - Effect: "Allow"
          Action:
            - "iam:ListAccountAliases"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource: "arn:aws:ssm:ap-southeast-2:186519255627:parameter/Slack/aws-billing-to-slack/webhook-url"
        - Effect: "Allow"
          Action:
            - "kms:Decrypt"
          Resource: "arn:aws:kms:ap-southeast-2:186519255627:key/ced31a12-a70d-4453-9d7b-8a6bf327ac26"

functions:
  report_cost:
    handler: handler.report_cost

    description: Send account daily billing data to Slack channel

    # Keep costs minimal
    memorySize: 128
    timeout: 10

    events:
      # Every day at 22:00 UTC / 8am AEST / 9am AEDT
      - schedule: cron(0 22 * * ? *)

    environment:
      AWS_ACCOUNT_NAME: ${param:aws_account, ''}
      CREDITS_EXPIRE_DATE: ${param:credits_expire_date, ''}
      CREDITS_REMAINING_AS_OF: ${param:credits_remaining_date, ''}
      CREDITS_REMAINING: ${param:credits_remaining, ''}
