version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  deploy_serverless:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run: |
          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-role \
          --role-arn arn:aws:iam::186519255627:role/circleci-data-deployments-role \
          --role-session-name snowflfake-databases-deploy \
          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
          --output text))
          export 
          serverless deploy --stage="prod"


workflows:
  deploy:
    jobs:
      - deploy_serverless:
          filters:
            branches:
              only:
                - master
